### ISSUE TITLE
Install client only

### ISSUE THREAD

**Issue by arturmartins** [ANXS/postgresql#179]
It would be great to have the following 2 flags:

install_server: no 
install_client: yes

So that I would only need one role.

**Comment by jlozadad** [comment]
is this still needed?

**Comment by flotho** [comment]
Hi,

I love the idea of @arturmartins , the idea is that sometimes solutions could be installed in separate server so that client and server has to be be installed on separate servers with the same version.
And moreover, working with this single awesome role will ease all the process.
IMHO this one is still needed

**Comment by thbar** [comment]
While the idea is interesting, per https://github.com/ANXS/postgresql/pull/207#issuecomment-464056566 I believe the role is not going to see an implementation of this.
