### ISSUE TITLE
remove versions that are no longer supported

### ISSUE THREAD

**Issue by jlozadad** [ANXS/postgresql#323]
https://yum.postgresql.org/

**Comment by jlozadad** [comment]
9.3 to 9.6 then 10,

**Comment by gclough** [comment]
@jlozadad , it makes sense to stay current, but should we leave the v9.3 and earlier code in the role and just mark it as unsupported?  Ideally everyone should have moved off of these versions by now, but there's always exceptions to this rule due to outside influences... and I'd hate to start removing templates that people rely on.

I'm not suggesting that we guarantee older versions will continue to work, just that we won't deliberately remove the supporting code, templates, etc.

$0.02

**Comment by gclough** [comment]
I've updated the README.md to show that old versions are not supported, so is this enough or should we actively rip out the old code?
