### ISSUE TITLE
checkout old PRs and see if anything can be closed.

### ISSUE THREAD

**Issue by jlozadad** [ANXS/postgresql#332]
check which ones can be closed due to PRs already being merged, redundant or causing conflicts.

**Comment by gclough** [comment]
@jlozadad, the PR's that I'm actively working on are:

#286 - Verify pg version
#287 - Allow use of "--data-checksums",'--xlogdir / --waldir", and "--pwfile" during initdb
#289 - Allow multiple clusters on RedHat
#294 - Only restart the cluster when absolutely necessary, otherwise reload
#300 - Updated synchronous_standby_names to be correct
#301 - New structure to allow "tuning" during deploy without using pg_tune
#303 - Convert ssl to redhat standard
#310 - Fix PostGIS install
#315 - Crossshcek, and fix all missing parameters, defaults, etc.

If you need anything changed, then please let me know.  Alternatively, how can we ask folks to review/comment on them?  I've not got a lot of time left before I will be dragged onto another project, so I'd like to fix anything and get them merged ASAP.

**Comment by jlozadad** [comment]
not sure. we have active folks but, not much. i would to prefer to have others give more feedback and testing to avoid being bias. ill try to test ur PRs in the few days.

**Comment by jlozadad** [comment]
@gclough I tried to look through the PR's and test em but, it looks like you are still working on em. Let me know what you have done and I'll will try to test and merge.

**Comment by jlozadad** [comment]
this looks like a good idea to do https://github.com/ANXS/postgresql/pull/247

**Comment by gclough** [comment]
@jlozadad ... yes #247 makes sense, and I was working on some code to do that.  A database without backups is a dangerous thing, so we should make it easy to setup automatic daily backups.  `pg_dump` isn't my favourite option, as `pg_basebackup`, or something like `barman` or `pgBackRest` is probably even better.

Should we reopen it?

As for the rest of the PR's.  I think that they are done, but I did try to merge some of them with the master to make life a little easier for you.  I did a merge of all of them into a local branch for my use, and there weren't many conflicts.  If you need me to do anything with this, or have any questions then please let me know.

Don't consider them as a single block, as I've tried to split each feature/fix into a separate PR.  If you consider any of them as OK, then merge those parts and I'll rebase as necessary.

**Comment by jlozadad** [comment]
so for 247 we can use the postgresql module since it can do backups. i'll keep testing other things.

**Comment by gclough** [comment]
@jlozadad , most of the work I'm doing on these PR's is to merge in changes to the master branch.  I've got them all merged into a local branch I'm using internally, so I'm pretty sure they play well together.

If you have any questions or comments on them, please let me know.

**Comment by gclough** [comment]
I'm doing a cleanup now, merging PR's that can, and closing relates issues.
