### ISSUE TITLE
Change tests using Molecule

### ISSUE THREAD

**Issue by tgadiev** [ANXS/postgresql#449]
I'd like to make tests for this role more convenient to modern technics. Molecule is the best testing framework for Ansible roles. This role is very useful and I think it needs more advanced tests.

**Comment by gclough** [comment]
@tgadiev , if you have a way to make things better... then I'll happily help review and merge it.  I inherited the current setup, so I'm not an expert.  Could you detail a bit more about how Molecule is "the best"?

If you're proposing wholesale changes, then we should include @jlozadad , @otakup0pe , and @UnderGreen at a minimum.

**Comment by otakup0pe** [comment]
I'm :100: on board with molecule and have been trying to find time to experiment on a shared setup which could be used across the ANXS collection.

**Comment by maglub** [comment]
I have started working on this and will make a skeleton that will work with our .travis-ci integration. Will deliver a first pull request to a separate branch quite soon.

I will initially base the docker containers on geerlingguy's systemd ready containers (so that we don't have to maintain them ourselves, and he is a decent source).

https://github.com/geerlingguy?tab=repositories&q=docker-*-ansible&type=&language=

What we should do as a first sttep:

* Set up a simple molecule scaffolding that initially only tests "converge" and "itempotency"
* Ansible-lint
* Yamllint
* Ansible-playbook install versions 9.5 - 13
* Covering debian, centos, ubuntu

Further work:

* Extend the geerlingguy's containers, as they run the playbook connecting as the user `root`, which means that we don't cover the important use case when the `ansible_user != root`.
* Add more tests

**Comment by otakup0pe** [comment]
> Will deliver a first pull request to a separate branch quite soon.

Oh this is quite exciting. I look forward to seeing your implementation! Hopefully it's something that can be adopted across the other ANXS roles - they currently all follow more or less the same dated vagrant based pattern.

Let me know if you want access to the https://github.com/anxs/scaffolding repo, for any scaffolding kinda bits.

**Comment by thbar** [comment]
Work in https://github.com/ANXS/postgresql/pull/511 has been merged - @maglub can this issue be closed for now?

**Comment by maglub** [comment]
Sure
